#!/usr/bin/env bash
# Transfer a file to server

if [ $# -lt 4 ]
then
       echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# diabling strict host key cheking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "path_to_file" "$username@ip:~/"

# checking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "FILE TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
