#!/usr/bin/env bash
# customizing 404 page

sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Holberton School" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtu.be\/dQw4w9WgXcQ?si=54Fqf98_gBlmghYn permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating 404 error page 

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default


# Restarting nginx after changes
sudo service nginx restart
